# Generated by Django 5.2.3 on 2025-06-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('nivel_riesgo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.muestra')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('genes_detectados', models.TextField(blank=True)),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.muestra')),
            ],
        ),
    ]
